// GastroBridge: Database types
// This file will be auto-generated by `npx supabase gen types typescript`
// For now, we define the types manually to match our schema

export type UserRole = "restaurant" | "supplier" | "admin";
export type CuisineType =
  | "italiana"
  | "pizzeria"
  | "pesce"
  | "carne"
  | "giapponese"
  | "fusion"
  | "bistrot"
  | "trattoria"
  | "gourmet"
  | "altro";
export type UnitType =
  | "kg"
  | "g"
  | "lt"
  | "ml"
  | "pz"
  | "cartone"
  | "bottiglia"
  | "latta"
  | "confezione"
  // Phase 1 English additions (extend existing enum, non-breaking)
  | "piece"
  | "l"
  | "box"
  | "pallet"
  | "bundle"
  | "other";
export type OrderStatus =
  | "draft"
  | "submitted"
  | "confirmed"
  | "preparing"
  | "shipping"
  | "delivered"
  | "cancelled";
export type PlanType =
  | "free"
  | "pro"
  | "business"
  | "base"
  | "growth"
  | "enterprise";
export type QualityTier = "economy" | "standard" | "premium" | "luxury";
export type CategoryMacro =
  | "carne"
  | "pesce"
  | "verdura"
  | "frutta"
  | "latticini"
  | "secco"
  | "bevande"
  | "surgelati"
  | "panetteria"
  | "altro";
export type CertificationType =
  | "DOP"
  | "IGP"
  | "STG"
  | "BIO"
  | "DOC"
  | "DOCG"
  | "IGT"
  | "HALAL"
  | "KOSHER"
  | "MSC"
  | "ASC"
  | "FAIRTRADE";
export type PresetProfile =
  | "custom"
  | "stellato"
  | "trattoria"
  | "pizzeria"
  | "bar"
  | "mensa";

// ------------------------------------------------------------------
// Phase 1 — Supplier Fondamenta: new enums
// ------------------------------------------------------------------
export type SupplierRole = "admin" | "sales" | "warehouse" | "driver";

export type SupplierPermission =
  | "order.read"
  | "order.accept_line"
  | "order.prepare"
  | "pricing.read"
  | "pricing.edit"
  | "catalog.read"
  | "catalog.edit"
  | "stock.read"
  | "stock.receive"
  | "stock.adjust"
  | "ddt.generate"
  | "ddt.manage_templates"
  | "delivery.plan"
  | "delivery.execute"
  | "staff.manage"
  | "settings.manage"
  | "analytics.financial"
  | "reviews.reply";

export type StockMovementType =
  | "receive"
  | "order_reserve"
  | "order_unreserve"
  | "order_ship"
  | "adjust_in"
  | "adjust_out"
  | "return"
  | "transfer";

export type OrderLineStatus =
  | "pending"
  | "accepted"
  | "modified"
  | "rejected";

export type OrderSplitEventType =
  | "received"
  | "accepted"
  | "partially_accepted"
  | "rejected"
  | "stock_conflict"
  | "preparing"
  | "packed"
  | "shipped"
  | "delivered"
  | "canceled";

export type DeliveryStatus =
  | "planned"
  | "loaded"
  | "in_transit"
  | "delivered"
  | "failed";

export type DdtCausale =
  | "sale"
  | "consignment"
  | "return"
  | "transfer"
  | "sample"
  | "cancel";

export type PromotionType = "percentage" | "fixed_amount" | "bundle";

export type NotificationChannel = "email" | "push" | "sms";

export type NotificationEvent =
  | "order_received"
  | "order_accepted"
  | "order_shipped"
  | "order_delivered"
  | "stock_low"
  | "lot_expiring"
  | "delivery_failed"
  | "reorder_suggested";

export type PromotionAppliesTo =
  | "all_catalog"
  | "categories"
  | "products"
  | "customers_segment";

// ------------------------------------------------------------------
// Cassetto Fiscale — Phase 1: new enums
// ------------------------------------------------------------------
export type FiscalProvider =
  | "tilby"
  | "cassa_in_cloud"
  | "lightspeed"
  | "scloby"
  | "tcpos"
  | "revo"
  | "simphony"
  | "hiopos"
  | "generic_webhook"
  | "csv_upload";

export type FiscalIntegrationStatus =
  | "pending_auth"
  | "active"
  | "paused"
  | "error"
  | "revoked";

export type FiscalReceiptStatus =
  | "issued"
  | "voided"
  | "refunded"
  | "partial_refund";

export type ReorderUrgency = "low" | "medium" | "high" | "critical";

export type ReorderSuggestionState =
  | "open"
  | "acted"
  | "dismissed"
  | "expired";

export type FiscalPosItemMappingSource = "user" | "auto_heuristic" | "ml";

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          role: UserRole;
          company_name: string;
          vat_number: string | null;
          phone: string | null;
          avatar_url: string | null;
          address: string | null;
          city: string | null;
          province: string | null;
          zip_code: string | null;
          latitude: number | null;
          longitude: number | null;
          onboarding_completed: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          role: UserRole;
          company_name: string;
          vat_number?: string | null;
          phone?: string | null;
          avatar_url?: string | null;
          address?: string | null;
          city?: string | null;
          province?: string | null;
          zip_code?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          onboarding_completed?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          role?: UserRole;
          company_name?: string;
          vat_number?: string | null;
          phone?: string | null;
          avatar_url?: string | null;
          address?: string | null;
          city?: string | null;
          province?: string | null;
          zip_code?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          onboarding_completed?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      restaurants: {
        Row: {
          id: string;
          profile_id: string;
          name: string;
          cuisine: CuisineType | null;
          covers: number | null;
          address: string | null;
          city: string | null;
          province: string | null;
          zip_code: string | null;
          latitude: number | null;
          longitude: number | null;
          phone: string | null;
          email: string | null;
          website: string | null;
          opening_hours: Record<string, unknown> | null;
          is_primary: boolean;
          monthly_budget_eur: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          name: string;
          cuisine?: CuisineType | null;
          covers?: number | null;
          address?: string | null;
          city?: string | null;
          province?: string | null;
          zip_code?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          phone?: string | null;
          email?: string | null;
          website?: string | null;
          opening_hours?: Record<string, unknown> | null;
          is_primary?: boolean;
          monthly_budget_eur?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string;
          name?: string;
          cuisine?: CuisineType | null;
          covers?: number | null;
          address?: string | null;
          city?: string | null;
          province?: string | null;
          zip_code?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          phone?: string | null;
          email?: string | null;
          website?: string | null;
          opening_hours?: Record<string, unknown> | null;
          is_primary?: boolean;
          monthly_budget_eur?: number | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      suppliers: {
        Row: {
          id: string;
          profile_id: string;
          company_name: string;
          description: string | null;
          logo_url: string | null;
          cover_url: string | null;
          website: string | null;
          email: string | null;
          phone: string | null;
          address: string | null;
          city: string | null;
          province: string | null;
          zip_code: string | null;
          latitude: number | null;
          longitude: number | null;
          min_order_amount: number | null;
          delivery_days: Record<string, unknown> | null;
          delivery_hours: Record<string, unknown> | null;
          certifications: string[] | null;
          rating_avg: number;
          rating_count: number;
          is_verified: boolean;
          is_active: boolean;
          delivery_schedule: Record<string, unknown> | null;
          payment_terms_days: number;
          cold_chain_available: boolean;
          // Phase 1
          fiscal_code: string | null;
          rea_number: string | null;
          sdi_code: string | null;
          default_ddt_template_id: string | null;
          feature_flags: Record<string, unknown>;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          company_name: string;
          description?: string | null;
          logo_url?: string | null;
          cover_url?: string | null;
          website?: string | null;
          email?: string | null;
          phone?: string | null;
          address?: string | null;
          city?: string | null;
          province?: string | null;
          zip_code?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          min_order_amount?: number | null;
          delivery_days?: Record<string, unknown> | null;
          delivery_hours?: Record<string, unknown> | null;
          certifications?: string[] | null;
          rating_avg?: number;
          rating_count?: number;
          is_verified?: boolean;
          is_active?: boolean;
          delivery_schedule?: Record<string, unknown> | null;
          payment_terms_days?: number;
          cold_chain_available?: boolean;
          fiscal_code?: string | null;
          rea_number?: string | null;
          sdi_code?: string | null;
          default_ddt_template_id?: string | null;
          feature_flags?: Record<string, unknown>;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string;
          company_name?: string;
          description?: string | null;
          logo_url?: string | null;
          cover_url?: string | null;
          website?: string | null;
          email?: string | null;
          phone?: string | null;
          address?: string | null;
          city?: string | null;
          province?: string | null;
          zip_code?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          min_order_amount?: number | null;
          delivery_days?: Record<string, unknown> | null;
          delivery_hours?: Record<string, unknown> | null;
          certifications?: string[] | null;
          rating_avg?: number;
          rating_count?: number;
          is_verified?: boolean;
          is_active?: boolean;
          delivery_schedule?: Record<string, unknown> | null;
          payment_terms_days?: number;
          cold_chain_available?: boolean;
          fiscal_code?: string | null;
          rea_number?: string | null;
          sdi_code?: string | null;
          default_ddt_template_id?: string | null;
          feature_flags?: Record<string, unknown>;
          created_at?: string;
          updated_at?: string;
        };
      };
      categories: {
        Row: {
          id: string;
          name: string;
          slug: string;
          icon: string | null;
          sort_order: number;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          icon?: string | null;
          sort_order?: number;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          icon?: string | null;
          sort_order?: number;
        };
      };
      subcategories: {
        Row: {
          id: string;
          category_id: string;
          name: string;
          slug: string;
          sort_order: number;
        };
        Insert: {
          id?: string;
          category_id: string;
          name: string;
          slug: string;
          sort_order?: number;
        };
        Update: {
          id?: string;
          category_id?: string;
          name?: string;
          slug?: string;
          sort_order?: number;
        };
      };
      products: {
        Row: {
          id: string;
          supplier_id: string;
          category_id: string;
          subcategory_id: string | null;
          name: string;
          description: string | null;
          brand: string | null;
          sku: string | null;
          unit: UnitType;
          price: number;
          min_quantity: number;
          max_quantity: number | null;
          image_url: string | null;
          certifications: string[] | null;
          origin: string | null;
          is_available: boolean;
          is_featured: boolean;
          quality_tier: QualityTier;
          is_bio: boolean;
          lead_time_days: number;
          packaging_size: number | null;
          packaging_unit: string | null;
          certifications_structured: CertificationType[];
          cold_chain_required: boolean;
          origin_country: string | null;
          origin_region: string | null;
          macro_category: CategoryMacro;
          // Phase 1
          default_warehouse_id: string | null;
          hazard_class: string | null;
          tax_rate: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          supplier_id: string;
          category_id: string;
          subcategory_id?: string | null;
          name: string;
          description?: string | null;
          brand?: string | null;
          sku?: string | null;
          unit: UnitType;
          price: number;
          min_quantity?: number;
          max_quantity?: number | null;
          image_url?: string | null;
          certifications?: string[] | null;
          origin?: string | null;
          is_available?: boolean;
          is_featured?: boolean;
          quality_tier?: QualityTier;
          is_bio?: boolean;
          lead_time_days?: number;
          packaging_size?: number | null;
          packaging_unit?: string | null;
          certifications_structured?: CertificationType[];
          cold_chain_required?: boolean;
          origin_country?: string | null;
          origin_region?: string | null;
          macro_category?: CategoryMacro;
          default_warehouse_id?: string | null;
          hazard_class?: string | null;
          tax_rate?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          supplier_id?: string;
          category_id?: string;
          subcategory_id?: string | null;
          name?: string;
          description?: string | null;
          brand?: string | null;
          sku?: string | null;
          unit?: UnitType;
          price?: number;
          min_quantity?: number;
          max_quantity?: number | null;
          image_url?: string | null;
          certifications?: string[] | null;
          origin?: string | null;
          is_available?: boolean;
          is_featured?: boolean;
          quality_tier?: QualityTier;
          is_bio?: boolean;
          lead_time_days?: number;
          packaging_size?: number | null;
          packaging_unit?: string | null;
          certifications_structured?: CertificationType[];
          cold_chain_required?: boolean;
          origin_country?: string | null;
          origin_region?: string | null;
          macro_category?: CategoryMacro;
          default_warehouse_id?: string | null;
          hazard_class?: string | null;
          tax_rate?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      orders: {
        Row: {
          id: string;
          restaurant_id: string;
          total: number;
          status: OrderStatus;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          restaurant_id: string;
          total?: number;
          status?: OrderStatus;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          restaurant_id?: string;
          total?: number;
          status?: OrderStatus;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      order_items: {
        Row: {
          id: string;
          order_id: string;
          product_id: string;
          supplier_id: string;
          quantity: number;
          unit_price: number;
          subtotal: number;
          notes: string | null;
          // Phase 1
          sales_unit_id: string | null;
        };
        Insert: {
          id?: string;
          order_id: string;
          product_id: string;
          supplier_id: string;
          quantity: number;
          unit_price: number;
          subtotal: number;
          notes?: string | null;
          sales_unit_id?: string | null;
        };
        Update: {
          id?: string;
          order_id?: string;
          product_id?: string;
          supplier_id?: string;
          quantity?: number;
          unit_price?: number;
          subtotal?: number;
          notes?: string | null;
          sales_unit_id?: string | null;
        };
      };
      order_splits: {
        Row: {
          id: string;
          order_id: string;
          supplier_id: string;
          subtotal: number;
          status: OrderStatus;
          confirmed_at: string | null;
          shipped_at: string | null;
          delivered_at: string | null;
          supplier_notes: string | null;
          // Phase 1
          warehouse_id: string | null;
          assigned_sales_member_id: string | null;
          expected_delivery_date: string | null;
          delivery_zone_id: string | null;
        };
        Insert: {
          id?: string;
          order_id: string;
          supplier_id: string;
          subtotal?: number;
          status?: OrderStatus;
          confirmed_at?: string | null;
          shipped_at?: string | null;
          delivered_at?: string | null;
          supplier_notes?: string | null;
          warehouse_id?: string | null;
          assigned_sales_member_id?: string | null;
          expected_delivery_date?: string | null;
          delivery_zone_id?: string | null;
        };
        Update: {
          id?: string;
          order_id?: string;
          supplier_id?: string;
          subtotal?: number;
          status?: OrderStatus;
          confirmed_at?: string | null;
          shipped_at?: string | null;
          delivered_at?: string | null;
          supplier_notes?: string | null;
          warehouse_id?: string | null;
          assigned_sales_member_id?: string | null;
          expected_delivery_date?: string | null;
          delivery_zone_id?: string | null;
        };
      };
      reviews: {
        Row: {
          id: string;
          restaurant_id: string | null;
          supplier_id: string | null;
          order_id: string | null;
          rating: number;
          quality_rating: number | null;
          delivery_rating: number | null;
          service_rating: number | null;
          comment: string | null;
          supplier_reply: string | null;
          supplier_replied_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          restaurant_id?: string | null;
          supplier_id?: string | null;
          order_id?: string | null;
          rating: number;
          quality_rating?: number | null;
          delivery_rating?: number | null;
          service_rating?: number | null;
          comment?: string | null;
          supplier_reply?: string | null;
          supplier_replied_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          restaurant_id?: string | null;
          supplier_id?: string | null;
          order_id?: string | null;
          rating?: number;
          quality_rating?: number | null;
          delivery_rating?: number | null;
          service_rating?: number | null;
          comment?: string | null;
          supplier_reply?: string | null;
          supplier_replied_at?: string | null;
          created_at?: string;
        };
      };
      subscriptions: {
        Row: {
          id: string;
          profile_id: string | null;
          plan: PlanType;
          stripe_customer_id: string | null;
          stripe_subscription_id: string | null;
          status: string;
          current_period_start: string | null;
          current_period_end: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          profile_id?: string | null;
          plan?: PlanType;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          status?: string;
          current_period_start?: string | null;
          current_period_end?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string | null;
          plan?: PlanType;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          status?: string;
          current_period_start?: string | null;
          current_period_end?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      price_history: {
        Row: {
          id: string;
          product_id: string | null;
          price: number;
          recorded_at: string;
        };
        Insert: {
          id?: string;
          product_id?: string | null;
          price: number;
          recorded_at?: string;
        };
        Update: {
          id?: string;
          product_id?: string | null;
          price?: number;
          recorded_at?: string;
        };
      };
      delivery_zones: {
        Row: {
          id: string;
          supplier_id: string | null;
          zone_name: string | null;
          provinces: string[] | null;
          zip_codes: string[] | null;
          delivery_fee: number;
          free_delivery_above: number | null;
          created_at: string;
          // Phase 1
          delivery_days: number[] | null;
          cutoff_time: string | null;
          delivery_slots: Record<string, unknown> | null;
          warehouse_id: string | null;
        };
        Insert: {
          id?: string;
          supplier_id?: string | null;
          zone_name?: string | null;
          provinces?: string[] | null;
          zip_codes?: string[] | null;
          delivery_fee?: number;
          free_delivery_above?: number | null;
          created_at?: string;
          delivery_days?: number[] | null;
          cutoff_time?: string | null;
          delivery_slots?: Record<string, unknown> | null;
          warehouse_id?: string | null;
        };
        Update: {
          id?: string;
          supplier_id?: string | null;
          zone_name?: string | null;
          provinces?: string[] | null;
          zip_codes?: string[] | null;
          delivery_fee?: number;
          free_delivery_above?: number | null;
          created_at?: string;
          delivery_days?: number[] | null;
          cutoff_time?: string | null;
          delivery_slots?: Record<string, unknown> | null;
          warehouse_id?: string | null;
        };
      };
      saved_orders: {
        Row: {
          id: string;
          restaurant_id: string | null;
          name: string;
          items: Record<string, unknown>;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          restaurant_id?: string | null;
          name: string;
          items: Record<string, unknown>;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          restaurant_id?: string | null;
          name?: string;
          items?: Record<string, unknown>;
          created_at?: string;
          updated_at?: string;
        };
      };
      restaurant_preferences: {
        Row: {
          id: string;
          restaurant_id: string;
          min_order_max_eur: number | null;
          lead_time_max_days: number | null;
          required_certifications: CertificationType[];
          blocked_supplier_ids: string[];
          max_distance_km: number | null;
          price_weight: number;
          quality_weight: number;
          delivery_weight: number;
          prefer_bio: boolean;
          prefer_km0: boolean;
          preset_profile: PresetProfile;
          fiscal_enabled: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          restaurant_id: string;
          min_order_max_eur?: number | null;
          lead_time_max_days?: number | null;
          required_certifications?: CertificationType[];
          blocked_supplier_ids?: string[];
          max_distance_km?: number | null;
          price_weight?: number;
          quality_weight?: number;
          delivery_weight?: number;
          prefer_bio?: boolean;
          prefer_km0?: boolean;
          preset_profile?: PresetProfile;
          fiscal_enabled?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          restaurant_id?: string;
          min_order_max_eur?: number | null;
          lead_time_max_days?: number | null;
          required_certifications?: CertificationType[];
          blocked_supplier_ids?: string[];
          max_distance_km?: number | null;
          price_weight?: number;
          quality_weight?: number;
          delivery_weight?: number;
          prefer_bio?: boolean;
          prefer_km0?: boolean;
          preset_profile?: PresetProfile;
          fiscal_enabled?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      restaurant_category_preferences: {
        Row: {
          id: string;
          restaurant_id: string;
          macro_category: CategoryMacro;
          min_quality_tier: QualityTier | null;
          lead_time_max_days: number | null;
          required_certifications: CertificationType[];
          price_weight: number | null;
          quality_weight: number | null;
          delivery_weight: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          restaurant_id: string;
          macro_category: CategoryMacro;
          min_quality_tier?: QualityTier | null;
          lead_time_max_days?: number | null;
          required_certifications?: CertificationType[];
          price_weight?: number | null;
          quality_weight?: number | null;
          delivery_weight?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          restaurant_id?: string;
          macro_category?: CategoryMacro;
          min_quality_tier?: QualityTier | null;
          lead_time_max_days?: number | null;
          required_certifications?: CertificationType[];
          price_weight?: number | null;
          quality_weight?: number | null;
          delivery_weight?: number | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      // ----------------------------------------------------------
      // Phase 1 — Supplier Fondamenta: new tables
      // ----------------------------------------------------------
      warehouses: {
        Row: {
          id: string;
          supplier_id: string;
          name: string;
          address: string | null;
          city: string | null;
          province: string | null;
          zip_code: string | null;
          latitude: number | null;
          longitude: number | null;
          is_primary: boolean;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          supplier_id: string;
          name: string;
          address?: string | null;
          city?: string | null;
          province?: string | null;
          zip_code?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          is_primary?: boolean;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          supplier_id?: string;
          name?: string;
          address?: string | null;
          city?: string | null;
          province?: string | null;
          zip_code?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          is_primary?: boolean;
          is_active?: boolean;
          created_at?: string;
        };
      };
      supplier_members: {
        Row: {
          id: string;
          supplier_id: string;
          profile_id: string;
          role: SupplierRole;
          is_active: boolean;
          invited_at: string;
          accepted_at: string | null;
          invited_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          supplier_id: string;
          profile_id: string;
          role: SupplierRole;
          is_active?: boolean;
          invited_at?: string;
          accepted_at?: string | null;
          invited_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          supplier_id?: string;
          profile_id?: string;
          role?: SupplierRole;
          is_active?: boolean;
          invited_at?: string;
          accepted_at?: string | null;
          invited_by?: string | null;
          created_at?: string;
        };
      };
      role_permissions: {
        Row: {
          role: SupplierRole;
          permission: string;
        };
        Insert: {
          role: SupplierRole;
          permission: string;
        };
        Update: {
          role?: SupplierRole;
          permission?: string;
        };
      };
      product_sales_units: {
        Row: {
          id: string;
          product_id: string;
          label: string;
          unit_type: UnitType;
          conversion_to_base: number;
          is_base: boolean;
          barcode: string | null;
          moq: number;
          sort_order: number;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          product_id: string;
          label: string;
          unit_type?: UnitType;
          conversion_to_base: number;
          is_base?: boolean;
          barcode?: string | null;
          moq?: number;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          product_id?: string;
          label?: string;
          unit_type?: UnitType;
          conversion_to_base?: number;
          is_base?: boolean;
          barcode?: string | null;
          moq?: number;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
        };
      };
      stock_lots: {
        Row: {
          id: string;
          product_id: string;
          warehouse_id: string;
          lot_code: string;
          expiry_date: string | null;
          quantity_base: number;
          quantity_reserved_base: number;
          cost_per_base: number | null;
          received_at: string;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          product_id: string;
          warehouse_id: string;
          lot_code: string;
          expiry_date?: string | null;
          quantity_base?: number;
          quantity_reserved_base?: number;
          cost_per_base?: number | null;
          received_at?: string;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          product_id?: string;
          warehouse_id?: string;
          lot_code?: string;
          expiry_date?: string | null;
          quantity_base?: number;
          quantity_reserved_base?: number;
          cost_per_base?: number | null;
          received_at?: string;
          notes?: string | null;
          created_at?: string;
        };
      };
      stock_movements: {
        Row: {
          id: string;
          product_id: string;
          lot_id: string | null;
          warehouse_id: string;
          quantity_base: number;
          movement_type: StockMovementType;
          ref_order_split_id: string | null;
          ref_delivery_item_id: string | null;
          created_by_member_id: string | null;
          created_at: string;
          notes: string | null;
        };
        Insert: {
          id?: string;
          product_id: string;
          lot_id?: string | null;
          warehouse_id: string;
          quantity_base: number;
          movement_type: StockMovementType;
          ref_order_split_id?: string | null;
          ref_delivery_item_id?: string | null;
          created_by_member_id?: string | null;
          created_at?: string;
          notes?: string | null;
        };
        Update: {
          id?: string;
          product_id?: string;
          lot_id?: string | null;
          warehouse_id?: string;
          quantity_base?: number;
          movement_type?: StockMovementType;
          ref_order_split_id?: string | null;
          ref_delivery_item_id?: string | null;
          created_by_member_id?: string | null;
          created_at?: string;
          notes?: string | null;
        };
      };
      price_lists: {
        Row: {
          id: string;
          supplier_id: string;
          name: string;
          description: string | null;
          is_default: boolean;
          valid_from: string | null;
          valid_to: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          supplier_id: string;
          name: string;
          description?: string | null;
          is_default?: boolean;
          valid_from?: string | null;
          valid_to?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          supplier_id?: string;
          name?: string;
          description?: string | null;
          is_default?: boolean;
          valid_from?: string | null;
          valid_to?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      price_list_items: {
        Row: {
          id: string;
          price_list_id: string;
          product_id: string;
          sales_unit_id: string;
          price: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          price_list_id: string;
          product_id: string;
          sales_unit_id: string;
          price: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          price_list_id?: string;
          product_id?: string;
          sales_unit_id?: string;
          price?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      price_list_tier_discounts: {
        Row: {
          id: string;
          price_list_item_id: string;
          min_quantity: number;
          discount_pct: number;
          sort_order: number;
        };
        Insert: {
          id?: string;
          price_list_item_id: string;
          min_quantity: number;
          discount_pct: number;
          sort_order?: number;
        };
        Update: {
          id?: string;
          price_list_item_id?: string;
          min_quantity?: number;
          discount_pct?: number;
          sort_order?: number;
        };
      };
      promotions: {
        Row: {
          id: string;
          supplier_id: string;
          name: string;
          type: PromotionType;
          value: number;
          starts_at: string;
          ends_at: string;
          applies_to: PromotionAppliesTo;
          filter_ids: string[] | null;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          supplier_id: string;
          name: string;
          type: PromotionType;
          value: number;
          starts_at: string;
          ends_at: string;
          applies_to: PromotionAppliesTo;
          filter_ids?: string[] | null;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          supplier_id?: string;
          name?: string;
          type?: PromotionType;
          value?: number;
          starts_at?: string;
          ends_at?: string;
          applies_to?: PromotionAppliesTo;
          filter_ids?: string[] | null;
          is_active?: boolean;
          created_at?: string;
        };
      };
      customer_price_assignments: {
        Row: {
          id: string;
          supplier_id: string;
          restaurant_id: string;
          price_list_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          supplier_id: string;
          restaurant_id: string;
          price_list_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          supplier_id?: string;
          restaurant_id?: string;
          price_list_id?: string;
          created_at?: string;
        };
      };
      order_split_items: {
        Row: {
          id: string;
          order_split_id: string;
          order_item_id: string;
          product_id: string;
          sales_unit_id: string | null;
          quantity_requested: number;
          quantity_accepted: number | null;
          unit_price: number;
          status: OrderLineStatus;
          rejection_reason: string | null;
          notes: string | null;
          updated_at: string;
        };
        Insert: {
          id?: string;
          order_split_id: string;
          order_item_id: string;
          product_id: string;
          sales_unit_id?: string | null;
          quantity_requested: number;
          quantity_accepted?: number | null;
          unit_price: number;
          status?: OrderLineStatus;
          rejection_reason?: string | null;
          notes?: string | null;
          updated_at?: string;
        };
        Update: {
          id?: string;
          order_split_id?: string;
          order_item_id?: string;
          product_id?: string;
          sales_unit_id?: string | null;
          quantity_requested?: number;
          quantity_accepted?: number | null;
          unit_price?: number;
          status?: OrderLineStatus;
          rejection_reason?: string | null;
          notes?: string | null;
          updated_at?: string;
        };
      };
      order_split_events: {
        Row: {
          id: string;
          order_split_id: string;
          event_type: OrderSplitEventType;
          member_id: string | null;
          note: string | null;
          metadata: Record<string, unknown> | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          order_split_id: string;
          event_type: OrderSplitEventType;
          member_id?: string | null;
          note?: string | null;
          metadata?: Record<string, unknown> | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          order_split_id?: string;
          event_type?: OrderSplitEventType;
          member_id?: string | null;
          note?: string | null;
          metadata?: Record<string, unknown> | null;
          created_at?: string;
        };
      };
      deliveries: {
        Row: {
          id: string;
          order_split_id: string;
          warehouse_id: string;
          driver_member_id: string | null;
          scheduled_date: string;
          scheduled_slot: Record<string, unknown> | null;
          status: DeliveryStatus;
          delivered_at: string | null;
          recipient_signature_url: string | null;
          pod_photo_url: string | null;
          failure_reason: string | null;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          order_split_id: string;
          warehouse_id: string;
          driver_member_id?: string | null;
          scheduled_date: string;
          scheduled_slot?: Record<string, unknown> | null;
          status?: DeliveryStatus;
          delivered_at?: string | null;
          recipient_signature_url?: string | null;
          pod_photo_url?: string | null;
          failure_reason?: string | null;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          order_split_id?: string;
          warehouse_id?: string;
          driver_member_id?: string | null;
          scheduled_date?: string;
          scheduled_slot?: Record<string, unknown> | null;
          status?: DeliveryStatus;
          delivered_at?: string | null;
          recipient_signature_url?: string | null;
          pod_photo_url?: string | null;
          failure_reason?: string | null;
          notes?: string | null;
          created_at?: string;
        };
      };
      delivery_items: {
        Row: {
          id: string;
          delivery_id: string;
          order_split_item_id: string;
          lot_id: string;
          quantity_base: number;
          quantity_sales_unit: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          delivery_id: string;
          order_split_item_id: string;
          lot_id: string;
          quantity_base: number;
          quantity_sales_unit: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          delivery_id?: string;
          order_split_item_id?: string;
          lot_id?: string;
          quantity_base?: number;
          quantity_sales_unit?: number;
          created_at?: string;
        };
      };
      ddt_templates: {
        Row: {
          id: string;
          supplier_id: string;
          name: string;
          logo_url: string | null;
          primary_color: string | null;
          header_html: string | null;
          footer_html: string | null;
          conditions_text: string | null;
          is_default: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          supplier_id: string;
          name: string;
          logo_url?: string | null;
          primary_color?: string | null;
          header_html?: string | null;
          footer_html?: string | null;
          conditions_text?: string | null;
          is_default?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          supplier_id?: string;
          name?: string;
          logo_url?: string | null;
          primary_color?: string | null;
          header_html?: string | null;
          footer_html?: string | null;
          conditions_text?: string | null;
          is_default?: boolean;
          created_at?: string;
        };
      };
      ddt_documents: {
        Row: {
          id: string;
          supplier_id: string;
          delivery_id: string;
          number: number;
          year: number;
          causale: DdtCausale;
          issued_at: string;
          recipient_snapshot: Record<string, unknown>;
          vettore: string | null;
          peso_kg: number | null;
          colli: number | null;
          pdf_url: string;
          canceled_at: string | null;
          canceled_reason: string | null;
          template_id: string | null;
        };
        Insert: {
          id?: string;
          supplier_id: string;
          delivery_id: string;
          number: number;
          year: number;
          causale: DdtCausale;
          issued_at?: string;
          recipient_snapshot: Record<string, unknown>;
          vettore?: string | null;
          peso_kg?: number | null;
          colli?: number | null;
          pdf_url: string;
          canceled_at?: string | null;
          canceled_reason?: string | null;
          template_id?: string | null;
        };
        Update: {
          id?: string;
          supplier_id?: string;
          delivery_id?: string;
          number?: number;
          year?: number;
          causale?: DdtCausale;
          issued_at?: string;
          recipient_snapshot?: Record<string, unknown>;
          vettore?: string | null;
          peso_kg?: number | null;
          colli?: number | null;
          pdf_url?: string;
          canceled_at?: string | null;
          canceled_reason?: string | null;
          template_id?: string | null;
        };
      };
      notification_preferences: {
        Row: {
          id: string;
          supplier_member_id: string;
          channel: NotificationChannel;
          event_type: NotificationEvent;
          enabled: boolean;
          updated_at: string;
        };
        Insert: {
          id?: string;
          supplier_member_id: string;
          channel: NotificationChannel;
          event_type: NotificationEvent;
          enabled?: boolean;
          updated_at?: string;
        };
        Update: {
          id?: string;
          supplier_member_id?: string;
          channel?: NotificationChannel;
          event_type?: NotificationEvent;
          enabled?: boolean;
          updated_at?: string;
        };
      };
      push_subscriptions: {
        Row: {
          id: string;
          profile_id: string;
          endpoint: string;
          p256dh: string;
          auth: string;
          user_agent: string | null;
          created_at: string;
          last_used_at: string | null;
        };
        Insert: {
          id?: string;
          profile_id: string;
          endpoint: string;
          p256dh: string;
          auth: string;
          user_agent?: string | null;
          created_at?: string;
          last_used_at?: string | null;
        };
        Update: {
          id?: string;
          profile_id?: string;
          endpoint?: string;
          p256dh?: string;
          auth?: string;
          user_agent?: string | null;
          created_at?: string;
          last_used_at?: string | null;
        };
      };
      // ------------------------------------------------------------
      // Cassetto Fiscale — Phase 1
      // ------------------------------------------------------------
      fiscal_integrations: {
        Row: {
          id: string;
          restaurant_id: string;
          provider: FiscalProvider;
          status: FiscalIntegrationStatus;
          display_name: string | null;
          credentials_encrypted: string | null;
          config: Record<string, unknown>;
          last_synced_at: string | null;
          last_error: string | null;
          webhook_secret: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          restaurant_id: string;
          provider: FiscalProvider;
          status?: FiscalIntegrationStatus;
          display_name?: string | null;
          credentials_encrypted?: string | null;
          config?: Record<string, unknown>;
          last_synced_at?: string | null;
          last_error?: string | null;
          webhook_secret?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          restaurant_id?: string;
          provider?: FiscalProvider;
          status?: FiscalIntegrationStatus;
          display_name?: string | null;
          credentials_encrypted?: string | null;
          config?: Record<string, unknown>;
          last_synced_at?: string | null;
          last_error?: string | null;
          webhook_secret?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      fiscal_raw_events: {
        Row: {
          id: number;
          integration_id: string;
          external_id: string;
          event_type: string;
          payload: Record<string, unknown>;
          received_at: string;
          processed_at: string | null;
          process_error: string | null;
        };
        Insert: {
          id?: number;
          integration_id: string;
          external_id: string;
          event_type: string;
          payload: Record<string, unknown>;
          received_at?: string;
          processed_at?: string | null;
          process_error?: string | null;
        };
        Update: {
          id?: number;
          integration_id?: string;
          external_id?: string;
          event_type?: string;
          payload?: Record<string, unknown>;
          received_at?: string;
          processed_at?: string | null;
          process_error?: string | null;
        };
      };
      fiscal_receipts: {
        Row: {
          id: string;
          restaurant_id: string;
          integration_id: string;
          external_id: string;
          issued_at: string;
          business_day: string;
          status: FiscalReceiptStatus;
          subtotal_cents: number;
          vat_cents: number;
          total_cents: number;
          payment_method: string | null;
          operator_name: string | null;
          table_ref: string | null;
          covers: number | null;
          metadata: Record<string, unknown>;
          created_at: string;
        };
        Insert: {
          id?: string;
          restaurant_id: string;
          integration_id: string;
          external_id: string;
          issued_at: string;
          business_day: string;
          status?: FiscalReceiptStatus;
          subtotal_cents: number;
          vat_cents: number;
          total_cents: number;
          payment_method?: string | null;
          operator_name?: string | null;
          table_ref?: string | null;
          covers?: number | null;
          metadata?: Record<string, unknown>;
          created_at?: string;
        };
        Update: {
          id?: string;
          restaurant_id?: string;
          integration_id?: string;
          external_id?: string;
          issued_at?: string;
          business_day?: string;
          status?: FiscalReceiptStatus;
          subtotal_cents?: number;
          vat_cents?: number;
          total_cents?: number;
          payment_method?: string | null;
          operator_name?: string | null;
          table_ref?: string | null;
          covers?: number | null;
          metadata?: Record<string, unknown>;
          created_at?: string;
        };
      };
      fiscal_receipt_items: {
        Row: {
          id: number;
          receipt_id: string;
          line_number: number;
          pos_item_id: string | null;
          name: string;
          category: string | null;
          quantity: number;
          unit_price_cents: number;
          subtotal_cents: number;
          vat_rate: number | null;
          discount_cents: number;
          is_voided: boolean;
        };
        Insert: {
          id?: number;
          receipt_id: string;
          line_number: number;
          pos_item_id?: string | null;
          name: string;
          category?: string | null;
          quantity: number;
          unit_price_cents: number;
          subtotal_cents: number;
          vat_rate?: number | null;
          discount_cents?: number;
          is_voided?: boolean;
        };
        Update: {
          id?: number;
          receipt_id?: string;
          line_number?: number;
          pos_item_id?: string | null;
          name?: string;
          category?: string | null;
          quantity?: number;
          unit_price_cents?: number;
          subtotal_cents?: number;
          vat_rate?: number | null;
          discount_cents?: number;
          is_voided?: boolean;
        };
      };
      fiscal_pos_items: {
        Row: {
          id: string;
          integration_id: string;
          pos_item_id: string;
          name: string;
          category: string | null;
          first_seen_at: string;
          last_seen_at: string;
          total_sold_cents: number;
          total_qty: number;
        };
        Insert: {
          id?: string;
          integration_id: string;
          pos_item_id: string;
          name: string;
          category?: string | null;
          first_seen_at?: string;
          last_seen_at?: string;
          total_sold_cents?: number;
          total_qty?: number;
        };
        Update: {
          id?: string;
          integration_id?: string;
          pos_item_id?: string;
          name?: string;
          category?: string | null;
          first_seen_at?: string;
          last_seen_at?: string;
          total_sold_cents?: number;
          total_qty?: number;
        };
      };
      fiscal_pos_item_mappings: {
        Row: {
          id: string;
          pos_item_id: string;
          gb_product_id: string | null;
          gb_category_id: string | null;
          depletion_ratio: number;
          source: FiscalPosItemMappingSource;
          confidence: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          pos_item_id: string;
          gb_product_id?: string | null;
          gb_category_id?: string | null;
          depletion_ratio?: number;
          source?: FiscalPosItemMappingSource;
          confidence?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          pos_item_id?: string;
          gb_product_id?: string | null;
          gb_category_id?: string | null;
          depletion_ratio?: number;
          source?: FiscalPosItemMappingSource;
          confidence?: number | null;
          created_at?: string;
        };
      };
      reorder_suggestions: {
        Row: {
          id: string;
          restaurant_id: string;
          product_id: string | null;
          category_id: string | null;
          suggested_qty: number | null;
          suggested_unit: string | null;
          estimated_coverage_days: number | null;
          urgency: ReorderUrgency;
          reason: string;
          preferred_supplier_id: string | null;
          snapshot: Record<string, unknown>;
          state: ReorderSuggestionState;
          acted_order_id: string | null;
          created_at: string;
          expires_at: string;
        };
        Insert: {
          id?: string;
          restaurant_id: string;
          product_id?: string | null;
          category_id?: string | null;
          suggested_qty?: number | null;
          suggested_unit?: string | null;
          estimated_coverage_days?: number | null;
          urgency: ReorderUrgency;
          reason: string;
          preferred_supplier_id?: string | null;
          snapshot: Record<string, unknown>;
          state?: ReorderSuggestionState;
          acted_order_id?: string | null;
          created_at?: string;
          expires_at?: string;
        };
        Update: {
          id?: string;
          restaurant_id?: string;
          product_id?: string | null;
          category_id?: string | null;
          suggested_qty?: number | null;
          suggested_unit?: string | null;
          estimated_coverage_days?: number | null;
          urgency?: ReorderUrgency;
          reason?: string;
          preferred_supplier_id?: string | null;
          snapshot?: Record<string, unknown>;
          state?: ReorderSuggestionState;
          acted_order_id?: string | null;
          created_at?: string;
          expires_at?: string;
        };
      };
    };
    Functions: {
      get_user_role: {
        Args: Record<string, never>;
        Returns: UserRole;
      };
      is_supplier_owner: {
        Args: { p_supplier_id: string };
        Returns: boolean;
      };
      is_restaurant_owner: {
        Args: { p_restaurant_id: string };
        Returns: boolean;
      };
      calculate_order_total: {
        Args: { p_order_id: string };
        Returns: number;
      };
      // Phase 1 — supplier membership helpers
      is_supplier_member: {
        Args: { p_supplier_id: string };
        Returns: boolean;
      };
      supplier_member_role: {
        Args: { p_supplier_id: string };
        Returns: SupplierRole | null;
      };
      has_supplier_permission: {
        Args: { p_supplier_id: string; p_permission: string };
        Returns: boolean;
      };
      next_ddt_number: {
        Args: { p_supplier_id: string; p_year: number };
        Returns: number;
      };
      // Cassetto Fiscale
      fiscal_owns_restaurant: {
        Args: { _restaurant_id: string; _user_id: string };
        Returns: boolean;
      };
      fiscal_is_enabled: {
        Args: { _restaurant_id: string };
        Returns: boolean;
      };
      fiscal_encrypt_credentials: {
        Args: { plaintext: Record<string, unknown> };
        Returns: string;
      };
      fiscal_decrypt_credentials: {
        Args: { ciphertext: string };
        Returns: Record<string, unknown>;
      };
      refresh_fiscal_aggregates: {
        Args: Record<string, never>;
        Returns: undefined;
      };
    };
    Enums: {
      user_role: UserRole;
      cuisine_type: CuisineType;
      unit_type: UnitType;
      order_status: OrderStatus;
      plan_type: PlanType;
      quality_tier: QualityTier;
      category_macro: CategoryMacro;
      certification_type: CertificationType;
      preset_profile: PresetProfile;
      // Phase 1
      supplier_role: SupplierRole;
      stock_movement_type: StockMovementType;
      order_line_status: OrderLineStatus;
      order_split_event_type: OrderSplitEventType;
      delivery_status: DeliveryStatus;
      ddt_causale: DdtCausale;
      promotion_type: PromotionType;
      notification_channel: NotificationChannel;
      notification_event: NotificationEvent;
      // Cassetto Fiscale
      fiscal_provider: FiscalProvider;
      fiscal_integration_status: FiscalIntegrationStatus;
      fiscal_receipt_status: FiscalReceiptStatus;
      reorder_urgency: ReorderUrgency;
    };
  };
}
