// GastroBridge: Database types
// This file will be auto-generated by `npx supabase gen types typescript`
// For now, we define the types manually to match our schema

export type UserRole = "restaurant" | "supplier" | "admin";
export type CuisineType =
  | "italiana"
  | "pizzeria"
  | "pesce"
  | "carne"
  | "giapponese"
  | "fusion"
  | "bistrot"
  | "trattoria"
  | "gourmet"
  | "altro";
export type UnitType =
  | "kg"
  | "g"
  | "lt"
  | "ml"
  | "pz"
  | "cartone"
  | "bottiglia"
  | "latta"
  | "confezione";
export type OrderStatus =
  | "draft"
  | "submitted"
  | "confirmed"
  | "preparing"
  | "shipping"
  | "delivered"
  | "cancelled";
export type PlanType =
  | "free"
  | "pro"
  | "business"
  | "base"
  | "growth"
  | "enterprise";
export type QualityTier = "economy" | "standard" | "premium" | "luxury";
export type CategoryMacro =
  | "carne"
  | "pesce"
  | "verdura"
  | "frutta"
  | "latticini"
  | "secco"
  | "bevande"
  | "surgelati"
  | "panetteria"
  | "altro";
export type CertificationType =
  | "DOP"
  | "IGP"
  | "STG"
  | "BIO"
  | "DOC"
  | "DOCG"
  | "IGT"
  | "HALAL"
  | "KOSHER"
  | "MSC"
  | "ASC"
  | "FAIRTRADE";
export type PresetProfile =
  | "custom"
  | "stellato"
  | "trattoria"
  | "pizzeria"
  | "bar"
  | "mensa";

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          role: UserRole;
          company_name: string;
          vat_number: string | null;
          phone: string | null;
          avatar_url: string | null;
          address: string | null;
          city: string | null;
          province: string | null;
          zip_code: string | null;
          latitude: number | null;
          longitude: number | null;
          onboarding_completed: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          role: UserRole;
          company_name: string;
          vat_number?: string | null;
          phone?: string | null;
          avatar_url?: string | null;
          address?: string | null;
          city?: string | null;
          province?: string | null;
          zip_code?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          onboarding_completed?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          role?: UserRole;
          company_name?: string;
          vat_number?: string | null;
          phone?: string | null;
          avatar_url?: string | null;
          address?: string | null;
          city?: string | null;
          province?: string | null;
          zip_code?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          onboarding_completed?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      restaurants: {
        Row: {
          id: string;
          profile_id: string;
          name: string;
          cuisine: CuisineType | null;
          covers: number | null;
          address: string | null;
          city: string | null;
          province: string | null;
          zip_code: string | null;
          latitude: number | null;
          longitude: number | null;
          phone: string | null;
          email: string | null;
          website: string | null;
          opening_hours: Record<string, unknown> | null;
          is_primary: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          name: string;
          cuisine?: CuisineType | null;
          covers?: number | null;
          address?: string | null;
          city?: string | null;
          province?: string | null;
          zip_code?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          phone?: string | null;
          email?: string | null;
          website?: string | null;
          opening_hours?: Record<string, unknown> | null;
          is_primary?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string;
          name?: string;
          cuisine?: CuisineType | null;
          covers?: number | null;
          address?: string | null;
          city?: string | null;
          province?: string | null;
          zip_code?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          phone?: string | null;
          email?: string | null;
          website?: string | null;
          opening_hours?: Record<string, unknown> | null;
          is_primary?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      suppliers: {
        Row: {
          id: string;
          profile_id: string;
          company_name: string;
          description: string | null;
          logo_url: string | null;
          cover_url: string | null;
          website: string | null;
          email: string | null;
          phone: string | null;
          address: string | null;
          city: string | null;
          province: string | null;
          zip_code: string | null;
          latitude: number | null;
          longitude: number | null;
          min_order_amount: number | null;
          delivery_days: Record<string, unknown> | null;
          delivery_hours: Record<string, unknown> | null;
          certifications: string[] | null;
          rating_avg: number;
          rating_count: number;
          is_verified: boolean;
          is_active: boolean;
          delivery_schedule: Record<string, unknown> | null;
          payment_terms_days: number;
          cold_chain_available: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          company_name: string;
          description?: string | null;
          logo_url?: string | null;
          cover_url?: string | null;
          website?: string | null;
          email?: string | null;
          phone?: string | null;
          address?: string | null;
          city?: string | null;
          province?: string | null;
          zip_code?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          min_order_amount?: number | null;
          delivery_days?: Record<string, unknown> | null;
          delivery_hours?: Record<string, unknown> | null;
          certifications?: string[] | null;
          rating_avg?: number;
          rating_count?: number;
          is_verified?: boolean;
          is_active?: boolean;
          delivery_schedule?: Record<string, unknown> | null;
          payment_terms_days?: number;
          cold_chain_available?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string;
          company_name?: string;
          description?: string | null;
          logo_url?: string | null;
          cover_url?: string | null;
          website?: string | null;
          email?: string | null;
          phone?: string | null;
          address?: string | null;
          city?: string | null;
          province?: string | null;
          zip_code?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          min_order_amount?: number | null;
          delivery_days?: Record<string, unknown> | null;
          delivery_hours?: Record<string, unknown> | null;
          certifications?: string[] | null;
          rating_avg?: number;
          rating_count?: number;
          is_verified?: boolean;
          is_active?: boolean;
          delivery_schedule?: Record<string, unknown> | null;
          payment_terms_days?: number;
          cold_chain_available?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      categories: {
        Row: {
          id: string;
          name: string;
          slug: string;
          icon: string | null;
          sort_order: number;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          icon?: string | null;
          sort_order?: number;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          icon?: string | null;
          sort_order?: number;
        };
      };
      subcategories: {
        Row: {
          id: string;
          category_id: string;
          name: string;
          slug: string;
          sort_order: number;
        };
        Insert: {
          id?: string;
          category_id: string;
          name: string;
          slug: string;
          sort_order?: number;
        };
        Update: {
          id?: string;
          category_id?: string;
          name?: string;
          slug?: string;
          sort_order?: number;
        };
      };
      products: {
        Row: {
          id: string;
          supplier_id: string;
          category_id: string;
          subcategory_id: string | null;
          name: string;
          description: string | null;
          brand: string | null;
          sku: string | null;
          unit: UnitType;
          price: number;
          min_quantity: number;
          max_quantity: number | null;
          image_url: string | null;
          certifications: string[] | null;
          origin: string | null;
          is_available: boolean;
          is_featured: boolean;
          quality_tier: QualityTier;
          is_bio: boolean;
          lead_time_days: number;
          packaging_size: number | null;
          packaging_unit: string | null;
          certifications_structured: CertificationType[];
          cold_chain_required: boolean;
          origin_country: string | null;
          origin_region: string | null;
          macro_category: CategoryMacro;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          supplier_id: string;
          category_id: string;
          subcategory_id?: string | null;
          name: string;
          description?: string | null;
          brand?: string | null;
          sku?: string | null;
          unit: UnitType;
          price: number;
          min_quantity?: number;
          max_quantity?: number | null;
          image_url?: string | null;
          certifications?: string[] | null;
          origin?: string | null;
          is_available?: boolean;
          is_featured?: boolean;
          quality_tier?: QualityTier;
          is_bio?: boolean;
          lead_time_days?: number;
          packaging_size?: number | null;
          packaging_unit?: string | null;
          certifications_structured?: CertificationType[];
          cold_chain_required?: boolean;
          origin_country?: string | null;
          origin_region?: string | null;
          macro_category?: CategoryMacro;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          supplier_id?: string;
          category_id?: string;
          subcategory_id?: string | null;
          name?: string;
          description?: string | null;
          brand?: string | null;
          sku?: string | null;
          unit?: UnitType;
          price?: number;
          min_quantity?: number;
          max_quantity?: number | null;
          image_url?: string | null;
          certifications?: string[] | null;
          origin?: string | null;
          is_available?: boolean;
          is_featured?: boolean;
          quality_tier?: QualityTier;
          is_bio?: boolean;
          lead_time_days?: number;
          packaging_size?: number | null;
          packaging_unit?: string | null;
          certifications_structured?: CertificationType[];
          cold_chain_required?: boolean;
          origin_country?: string | null;
          origin_region?: string | null;
          macro_category?: CategoryMacro;
          created_at?: string;
          updated_at?: string;
        };
      };
      orders: {
        Row: {
          id: string;
          restaurant_id: string;
          total: number;
          status: OrderStatus;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          restaurant_id: string;
          total?: number;
          status?: OrderStatus;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          restaurant_id?: string;
          total?: number;
          status?: OrderStatus;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      order_items: {
        Row: {
          id: string;
          order_id: string;
          product_id: string;
          supplier_id: string;
          quantity: number;
          unit_price: number;
          subtotal: number;
          notes: string | null;
        };
        Insert: {
          id?: string;
          order_id: string;
          product_id: string;
          supplier_id: string;
          quantity: number;
          unit_price: number;
          subtotal: number;
          notes?: string | null;
        };
        Update: {
          id?: string;
          order_id?: string;
          product_id?: string;
          supplier_id?: string;
          quantity?: number;
          unit_price?: number;
          subtotal?: number;
          notes?: string | null;
        };
      };
      order_splits: {
        Row: {
          id: string;
          order_id: string;
          supplier_id: string;
          subtotal: number;
          status: OrderStatus;
          confirmed_at: string | null;
          shipped_at: string | null;
          delivered_at: string | null;
          supplier_notes: string | null;
        };
        Insert: {
          id?: string;
          order_id: string;
          supplier_id: string;
          subtotal?: number;
          status?: OrderStatus;
          confirmed_at?: string | null;
          shipped_at?: string | null;
          delivered_at?: string | null;
          supplier_notes?: string | null;
        };
        Update: {
          id?: string;
          order_id?: string;
          supplier_id?: string;
          subtotal?: number;
          status?: OrderStatus;
          confirmed_at?: string | null;
          shipped_at?: string | null;
          delivered_at?: string | null;
          supplier_notes?: string | null;
        };
      };
      reviews: {
        Row: {
          id: string;
          restaurant_id: string | null;
          supplier_id: string | null;
          order_id: string | null;
          rating: number;
          quality_rating: number | null;
          delivery_rating: number | null;
          service_rating: number | null;
          comment: string | null;
          supplier_reply: string | null;
          supplier_replied_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          restaurant_id?: string | null;
          supplier_id?: string | null;
          order_id?: string | null;
          rating: number;
          quality_rating?: number | null;
          delivery_rating?: number | null;
          service_rating?: number | null;
          comment?: string | null;
          supplier_reply?: string | null;
          supplier_replied_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          restaurant_id?: string | null;
          supplier_id?: string | null;
          order_id?: string | null;
          rating?: number;
          quality_rating?: number | null;
          delivery_rating?: number | null;
          service_rating?: number | null;
          comment?: string | null;
          supplier_reply?: string | null;
          supplier_replied_at?: string | null;
          created_at?: string;
        };
      };
      subscriptions: {
        Row: {
          id: string;
          profile_id: string | null;
          plan: PlanType;
          stripe_customer_id: string | null;
          stripe_subscription_id: string | null;
          status: string;
          current_period_start: string | null;
          current_period_end: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          profile_id?: string | null;
          plan?: PlanType;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          status?: string;
          current_period_start?: string | null;
          current_period_end?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string | null;
          plan?: PlanType;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          status?: string;
          current_period_start?: string | null;
          current_period_end?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      price_history: {
        Row: {
          id: string;
          product_id: string | null;
          price: number;
          recorded_at: string;
        };
        Insert: {
          id?: string;
          product_id?: string | null;
          price: number;
          recorded_at?: string;
        };
        Update: {
          id?: string;
          product_id?: string | null;
          price?: number;
          recorded_at?: string;
        };
      };
      delivery_zones: {
        Row: {
          id: string;
          supplier_id: string | null;
          zone_name: string | null;
          provinces: string[] | null;
          zip_codes: string[] | null;
          delivery_fee: number;
          free_delivery_above: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          supplier_id?: string | null;
          zone_name?: string | null;
          provinces?: string[] | null;
          zip_codes?: string[] | null;
          delivery_fee?: number;
          free_delivery_above?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          supplier_id?: string | null;
          zone_name?: string | null;
          provinces?: string[] | null;
          zip_codes?: string[] | null;
          delivery_fee?: number;
          free_delivery_above?: number | null;
          created_at?: string;
        };
      };
      saved_orders: {
        Row: {
          id: string;
          restaurant_id: string | null;
          name: string;
          items: Record<string, unknown>;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          restaurant_id?: string | null;
          name: string;
          items: Record<string, unknown>;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          restaurant_id?: string | null;
          name?: string;
          items?: Record<string, unknown>;
          created_at?: string;
          updated_at?: string;
        };
      };
      restaurant_preferences: {
        Row: {
          id: string;
          restaurant_id: string;
          min_order_max_eur: number | null;
          lead_time_max_days: number | null;
          required_certifications: CertificationType[];
          blocked_supplier_ids: string[];
          max_distance_km: number | null;
          price_weight: number;
          quality_weight: number;
          delivery_weight: number;
          prefer_bio: boolean;
          prefer_km0: boolean;
          preset_profile: PresetProfile;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          restaurant_id: string;
          min_order_max_eur?: number | null;
          lead_time_max_days?: number | null;
          required_certifications?: CertificationType[];
          blocked_supplier_ids?: string[];
          max_distance_km?: number | null;
          price_weight?: number;
          quality_weight?: number;
          delivery_weight?: number;
          prefer_bio?: boolean;
          prefer_km0?: boolean;
          preset_profile?: PresetProfile;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          restaurant_id?: string;
          min_order_max_eur?: number | null;
          lead_time_max_days?: number | null;
          required_certifications?: CertificationType[];
          blocked_supplier_ids?: string[];
          max_distance_km?: number | null;
          price_weight?: number;
          quality_weight?: number;
          delivery_weight?: number;
          prefer_bio?: boolean;
          prefer_km0?: boolean;
          preset_profile?: PresetProfile;
          created_at?: string;
          updated_at?: string;
        };
      };
      restaurant_category_preferences: {
        Row: {
          id: string;
          restaurant_id: string;
          macro_category: CategoryMacro;
          min_quality_tier: QualityTier | null;
          lead_time_max_days: number | null;
          required_certifications: CertificationType[];
          price_weight: number | null;
          quality_weight: number | null;
          delivery_weight: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          restaurant_id: string;
          macro_category: CategoryMacro;
          min_quality_tier?: QualityTier | null;
          lead_time_max_days?: number | null;
          required_certifications?: CertificationType[];
          price_weight?: number | null;
          quality_weight?: number | null;
          delivery_weight?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          restaurant_id?: string;
          macro_category?: CategoryMacro;
          min_quality_tier?: QualityTier | null;
          lead_time_max_days?: number | null;
          required_certifications?: CertificationType[];
          price_weight?: number | null;
          quality_weight?: number | null;
          delivery_weight?: number | null;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Functions: {
      get_user_role: {
        Args: Record<string, never>;
        Returns: UserRole;
      };
      is_supplier_owner: {
        Args: { p_supplier_id: string };
        Returns: boolean;
      };
      is_restaurant_owner: {
        Args: { p_restaurant_id: string };
        Returns: boolean;
      };
      calculate_order_total: {
        Args: { p_order_id: string };
        Returns: number;
      };
    };
    Enums: {
      user_role: UserRole;
      cuisine_type: CuisineType;
      unit_type: UnitType;
      order_status: OrderStatus;
      plan_type: PlanType;
      quality_tier: QualityTier;
      category_macro: CategoryMacro;
      certification_type: CertificationType;
      preset_profile: PresetProfile;
    };
  };
}
